[tool.poetry]
name = "vox2docs"
version = "0.0.1"
description = "A system for processing voice recordings into transcripts and insights"
authors = ["Sergey Alexandrov <alexandrov88@gmail.com>"]
license = "MIT"
packages = [{ include = "vox2docs" }]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.8"
watchdog = "^6.0.0"
pydantic = "^2.10.5"
pyyaml = "^6.0.2"
rich = "^13.9.4"

[tool.poetry.scripts]
vox2docs = "vox2docs.cli:main"

[tool.poetry.group.dev.dependencies]
mypy = "^1.14.1"
types-pyyaml = "^6.0.12.20241230"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
